services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reloop-api
    env_file: .env
    environment:
      DATABASE_URL: "postgresql://reloop:basededatos@reloop-bd.c32ieac4emix.us-east-2.rds.amazonaws.com:5432/postgres?schema=public"
      NODE_ENV: production
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - uploads_data:/app/uploads
    restart: unless-stopped
    command: >
      sh -c "
      npx prisma generate &&
      npx prisma migrate deploy &&
      exec node src/server.js
      "

volumes:
  uploads_data:
